all:
	../../bin/cadeau -o output
	(cd init; ../../../bin/cadeau -o ../output/init_output)
	(cd struct; ../../../bin/cadeau -o ../output/struct_output)
	(cd metadata; ../../../bin/cadeau -o ../output/metadata_output)
